// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBaDOGkQta8N3jxN7waDURGhdReXJwhvE',
    appId: '1:617408916955:web:937cd96079a95bc4dccbfe',
    messagingSenderId: '617408916955',
    projectId: 'homey-ace12',
    authDomain: 'homey-ace12.firebaseapp.com',
    storageBucket: 'homey-ace12.appspot.com',
    measurementId: 'G-4P6LTKBV1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW7vkRTtOtLMU_tZyCqbNkV9Kkj8cCoEg',
    appId: '1:617408916955:android:ab14dcecd64188fedccbfe',
    messagingSenderId: '617408916955',
    projectId: 'homey-ace12',
    storageBucket: 'homey-ace12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB12al01eEHDHjzX5jFsPG--WnAN2Eh1VA',
    appId: '1:617408916955:ios:564412a60d346df1dccbfe',
    messagingSenderId: '617408916955',
    projectId: 'homey-ace12',
    storageBucket: 'homey-ace12.appspot.com',
    iosBundleId: 'com.example.homey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB12al01eEHDHjzX5jFsPG--WnAN2Eh1VA',
    appId: '1:617408916955:ios:c64e830f6b5e56b6dccbfe',
    messagingSenderId: '617408916955',
    projectId: 'homey-ace12',
    storageBucket: 'homey-ace12.appspot.com',
    iosBundleId: 'com.example.homey.RunnerTests',
  );
}
